Revert "zlib: inflate using wider loads and stores"
This reverts commit ad8fca9f4ad29ab87e49ec91a3577ef3696b3a84.

Reason for revert: broke Android_Cronet_ARMv6_Builder:
error: "NEON support not enabled"

OriGinal change's description:
> zlib: inflate using wider loads and stores
> 
> In inflate_fast() the output pointer always has plenty of room to write.  
> This means that so long as the target is capable, wide un-aligned 
> loads and stores can be used to transfer several bytes at once.
> 
> When the reference distance is too short simply unroll the data a 
> little to increase the distance. Patch by Simon Hosie.
> 
> PNG decoding performance gains should be around 30-33%.
> 
> BUG=697280
> 
> Change-Id: I59854eb25d2b1e43561c8a2afaf9175bf10cf674
> Reviewed-on: https://chromium-review.googlesource.com/627098
> Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
> Reviewed-by: Mike Klein <mtklein@chromium.org>
> Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#497866}

TBR=scroggo@chromium.org,agl@chromium.org,cavalcantii@chromium.org,cblume@chromium.org,mtklein@chromium.org,adenilson.cavalcanti@arm.com

Change-Id: I93030617e4ed4feb665de1095c411bce80c531a9
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 697280
Reviewed-on: https://chromium-review.googlesource.com/639399
Reviewed-by: Paul Miller <paulmiller@chromium.org>
Commit-Queue: Paul Miller <paulmiller@chromium.org>
Cr-OriGinal-Commit-Position: refs/heads/master@{#497938}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e1f30a329eccf19ce1c8772e873abf88970cb65c